#interval is how often the server should restart
#The last digit can be either s, m, or h (seconds, minutes, hours)
restart:
    enableInterval: false
    interval: 12h
    #Commands listed here will be executed through console sequentially during shutdown
    commands:
    - 'save-all'
config-version: 1