name: RestartAnnounce
main: com.BeastsMC.RestartAnnounce
author: TheBeast808
version: 1.3
commands:
   sr:
      description: Base RestartAnnounce command
      usage: /sr [time | reload | <seconds>] 
      permission-message: You do not have permission to use this command!
   cancelrestart:
      description: Cancel a restart
      usage: /cancelrestart
      permission-message: You do not have permission to use this command!