#interval is how often the server should restart
#The last digit can be either s, m, or h (seconds, minutes, hours)
restart:
    enableInterval: false
    interval: 12h
    #Commands listed here will be executed through console sequentially during shutdown
    commands:
    - 'save-all'
#Broadcasted to server when somebody schedules a restart to occur
broadcast-on-schedule:
    - '&bThe server has been scheduled to restart in %time% seconds'
    - '&bIt should be back up shortly afterwards, sorry for the inconvenience'

#Messages to broadcast a few seconds before shut down
broadcast-before-shutdown:
    - '&4Server is shutting down!'
    - '&4See you soon!'
config-version: 1